### ISSUE TITLE
Color of moving squares

### ISSUE THREAD

**Issue by Viper7171** [creativetimofficial/blk-design-system#1]
How do I change the colors of those floating squares on the main page that use header-filter? Like to bg-warning color.

**Comment by JKannekens** [comment]
You can change the colour of the moving squares by editing the blk-design-system.css. Find .index-page .squares its somewhere around line 16408. 

.index-page .squares {
  animation: move-left-right 1s infinite;
  background: #ba54f5;
  background: -webkit-linear-gradient(0deg, #ba54f5 0%, #e14eca 100%);
  background: -o-linear-gradient(0deg, #ba54f5 0%, #e14eca 100%);
  background: -moz-linear-gradient(0deg, #ba54f5 0%, #e14eca 100%);
  **background: linear-gradient(0deg, #ba54f5 0%, #e14eca 100%);**
  position: absolute;
  transition: 0.5s ease-out;
  overflow: hidden;
  border-radius: 20%;
}

(Change the highlighted gradient with your color)

**Comment by Viper7171** [comment]
Thanks

**Comment by adonix-dev** [comment]
- To change the color of the moving scuares if you use SCSS go in ```assets/scss/blk-design-systm/angular/_*page.scss``` ( default: _exemple-pages.scss )

- You can change the colors variables in ```assets/scss/blk-design-systm/custom/variables.scss``` 
( default : ```$danger-states``` and ```$danger```)
