### ISSUE TITLE
how use data-live-search

### ISSUE THREAD

**Issue by serome111** [creativetimofficial/blk-design-system#12]
how use data-live-search.  is not found in the documentation
reality
![image](https://user-images.githubusercontent.com/32885503/62737978-c0d83900-b9f6-11e9-9bc0-383151043f93.png)
expectative
![image](https://user-images.githubusercontent.com/32885503/62738043-ee24e700-b9f6-11e9-8b9b-3aa4b43e8169.png)

here the code and link to the bootstrap documentation
https://developer.snapappointments.com/bootstrap-select/examples/
<select class="selectpicker" data-live-search="true">
  <option data-tokens="ketchup mustard">Hot Dog, Fries and a Soda</option>
  <option data-tokens="mustard">Burger, Shake and a Smile</option>
  <option data-tokens="frosting">Sugar, Spice and all things nice</option>
</select>

When I try to add bootstrap. My design is damaged.
Can you help me?

**Comment by rarestoma** [comment]
Hi @serome111 and thank you for working with our products!

Unfortunately, we do not provide such a select so we do not have a style on it. We will see in our next update and maybe we will add it.

All the best,
Rares!
