### ISSUE TITLE
No `baseHref`s specified in angular.json, breaks router

### ISSUE THREAD

**Issue by Helveg** [creativetimofficial/blk-design-system#14]
Without the `baseHref` specified in the `options` of `angular.json` `ng serve` will inject `<script src="runtime.js">` etc, instead of `<script src="/runtime.js">` and entering the app by navigating to `http://localhost:4200/some/path/with/slashes` will break.

**Comment by chelaruc** [comment]
Hi, @Helveg. Thank you for using our product. Can you move this issue to the right repository(https://github.com/creativetimofficial/blk-design-system-angular/issues)?
