### ISSUE TITLE
Modal moves down further down the page when more elements are inside.

### ISSUE THREAD

**Issue by charliea21** [creativetimofficial/blk-design-system#15]
Hello. I am experiencing an annoying issue where a modal is places so far down the page depending on how many elements/content is in it.

Here's a GIF of the issue: https://gyazo.com/8db8085564672957fbb433eafd175651

**Comment by rarestoma** [comment]
Hi @charliea21,

Thank you for working with our products.

Please remove 'transform: translateY(30%)' from .modal.show .modal-dialog and now it should work properly.

I hope it helps.

All the best,
Rares

**Comment by charliea21** [comment]
Thank you. This has solved my issue.
