### ISSUE TITLE
Misalignment using input-group

### ISSUE THREAD

**Issue by tr32** [creativetimofficial/blk-design-system#16]
With the following code snippet using input-group on Blk Design System v1.0.0, I get a misalignment of input field and button:

```
<div class="row">    
    <div class="col-sm-5">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search...">
            <div class="input-group-append">
                <button type="button" class="btn btn-secondary">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="col-sm-7">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Type something...">
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-danger">Reset</button>
            </div>
        </div>
    </div>
</div>
```

![input_group_misalignment](https://user-images.githubusercontent.com/15521242/73260343-01588880-41ca-11ea-86c9-b3dfdcacf61b.PNG)

How can I fix this?

**Comment by rarestoma** [comment]
Hi @tr32,

Thank you for working with our products.

Please add the following lines in your css files:

`
.input-group .input-group-append .btn {
    padding: 10px 40px;
    margin-top: 0;
}
`

Please let me know if it works.

All the best,
Rares

**Comment by tr32** [comment]
Thank you! It worked.
