### ISSUE TITLE
Can't load transparent navbar

### ISSUE THREAD

**Issue by cloud-lib** [creativetimofficial/blk-design-system#6]
I put all resource in third party, then I write the code in codeigniter. But the transparent navbar didn't want to show the primary color when I scroll down.

**Comment by cloud-lib** [comment]
I run with xampp, if I run directly without codeigniter everything run as well

**Comment by rarestoma** [comment]
Hello,

Thank you for the interest in our products.

Our javascript removes the 'navbar-transparent' class from the navbar given to a color-on-scroll number. Are you sure you included everything?

All the best,
Rares

**Comment by cloud-lib** [comment]
it has solved, the last javascript also deleted when I delete demo.js
